# Generated by Django 6.0.2 on 2026-02-16 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('min_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contribution window',
                'verbose_name_plural': 'Contribution windows',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='common.member')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='common.contributionwindow')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
