# Generated by Django 6.0.2 on 2026-02-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contributionwindow_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionwindow',
            name='min_amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='contributionwindow',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
