# Generated by Django 6.0.2 on 2026-02-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_contributionwindow_min_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vehicle_type', models.CharField(choices=[('SAVINGS_ACCOUNT', 'Savings Account'), ('LAND', 'Land'), ('SHARES', 'Shares'), ('GOVERNMENT_BOND', 'Government Bond'), ('OTHER', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investment vehicle',
                'verbose_name_plural': 'Investment vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
