# Generated by Django 6.0.2 on 2026-03-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_investmentvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundReallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations_in', to='common.investmentvehicle')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_reallocations', to='common.member')),
                ('source_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations_out', to='common.investmentvehicle')),
            ],
            options={
                'verbose_name': 'Fund reallocation',
                'verbose_name_plural': 'Fund reallocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
