# Generated by Django 6.0.2 on 2026-03-21 14:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_fund_reallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentvehicle',
            name='current_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
    ]
