# Generated by Django 6.0.2 on 2026-03-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_investment_vehicle_current_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentvehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SAVINGS_ACCOUNT', 'Savings Account'), ('LAND', 'Land'), ('SHARES', 'Shares'), ('GOVERNMENT_BOND', 'Government Bond'), ('OTHER', 'Other'), ('UNALLOCATED', 'Unallocated Funds')], max_length=32),
        ),
        migrations.CreateModel(
            name='InvestmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=20)),
                ('share_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_events', to='common.investmentvehicle')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_investments', to='common.member')),
            ],
            options={
                'verbose_name': 'Investment event',
                'verbose_name_plural': 'Investment events',
                'ordering': ['-created_at'],
            },
        ),
    ]
