# Generated by Django 6.0.2 on 2026-03-21 15:04

from decimal import Decimal

from django.db import migrations
from django.db.models import Sum


def seed_unallocated_vehicle(apps, schema_editor):
    """
    Create the singleton unallocated-funds vehicle and backfill its balance
    from the sum of all existing contributions.
    """
    InvestmentVehicle = apps.get_model("common", "InvestmentVehicle")
    Contribution = apps.get_model("common", "Contribution")

    total = Contribution.objects.aggregate(total=Sum("amount"))["total"] or Decimal("0.0000")

    InvestmentVehicle.objects.get_or_create(
        vehicle_type="UNALLOCATED",
        defaults={
            "name": "Unallocated Funds",
            "description": "Pool of contributions not yet invested.",
            "current_value": total,
        },
    )


def reverse_seed(apps, schema_editor):
    InvestmentVehicle = apps.get_model("common", "InvestmentVehicle")
    InvestmentVehicle.objects.filter(vehicle_type="UNALLOCATED").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_investment_event_and_unallocated_type'),
    ]

    operations = [
        migrations.RunPython(seed_unallocated_vehicle, reverse_seed),
    ]
