# Generated by Django 6.0.2 on 2026-03-21 16:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_seed_unallocated_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOwnershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('equity_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cash_distributed', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('cash_pending', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_records', to='common.investmentvehicle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_ownership_records', to='common.member')),
            ],
            options={
                'verbose_name': 'Asset ownership record',
                'verbose_name_plural': 'Asset ownership records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberShareAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=4, max_digits=20)),
                ('share_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_allocations', to='common.investmentevent')),
                ('investment_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_allocations', to='common.investmentvehicle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_allocations', to='common.member')),
            ],
            options={
                'verbose_name': 'Member share allocation',
                'verbose_name_plural': 'Member share allocations',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NAVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_per_share', models.DecimalField(decimal_places=4, max_digits=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nav_records', to='common.investmentvehicle')),
            ],
            options={
                'verbose_name': 'NAV record',
                'verbose_name_plural': 'NAV records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
