# Generated by Django 6.0.2 on 2026-03-26 00:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_assetownershiprecord_membershareallocation_navrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timeline", models.CharField(choices=[("6_MONTHS", "6 months"), ("1_YEAR", "1 year"), ("2_YEARS", "2 years"), ("5_YEARS", "5 years"), ("10_YEARS", "10 years")], max_length=16)),
                ("target_amount", models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("member", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="goal", to="common.member")),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "ordering": ["-updated_at"],
            },
        ),
    ]
